"use client"

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'

export function AuthForm({ mode }: { mode: 'login' | 'register' }) {
  const router = useRouter(); const auth = useAuth(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(null); try { if (mode === 'login') await auth.login(email, password); else await auth.register(name, email, password); router.push('/dashboard'); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to authenticate') } finally { setPending(false) } }
  return <main className="flex min-h-screen items-center justify-center px-6 py-12"><form onSubmit={submit} className="w-full max-w-md space-y-5 rounded-2xl border border-border bg-card p-6 shadow-sm"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Leads AI</p><h1 className="mt-2 text-3xl font-semibold">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1></div>{mode === 'register' && <label className="block text-sm">Name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label>}<label className="block text-sm">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label><label className="block text-sm">Password<input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2" /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button disabled={pending} className="w-full rounded-lg bg-primary px-4 py-2 font-medium text-primary-foreground disabled:opacity-60">{pending ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form></main>
}
