import Link from 'next/link'
import { ArrowRight, BarChart3, Bot, Check, ChevronRight, Layers3, Sparkles, Workflow } from 'lucide-react'
import ProductPreview from '@/components/marketing/ProductPreview'

const features = [
  { title: 'Lead management', body: 'Create, organize, update, and manage your leads from one focused workspace.', icon: Layers3 },
  { title: 'Pipeline tracking', body: 'Track status and priority as opportunities move through your pipeline.', icon: Workflow },
  { title: 'Analytics', body: 'Understand your current pipeline using real data from your workspace.', icon: BarChart3 },
  { title: 'AI intelligence', body: 'AI-powered qualification and lead intelligence for the next stage of your workflow.', icon: Bot, badge: 'Coming soon' },
]

const steps = [['01', 'Capture', 'Add leads to your workspace.'], ['02', 'Organize', 'Manage status, priority, and lead information.'], ['03', 'Analyze', 'Understand your pipeline through analytics.'], ['04', 'Automate', 'Connect workflows when automation is enabled.']]

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <nav className="sticky top-4 z-20 mx-auto flex max-w-6xl items-center justify-between border border-border/70 bg-background/85 px-5 py-3 shadow-lg shadow-black/10 backdrop-blur-xl" aria-label="Main navigation"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-md bg-primary text-sm font-bold text-primary-foreground">L</span><span>LEADS AI</span></Link><div className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#product" className="transition-colors hover:text-foreground">Product</a><a href="#features" className="transition-colors hover:text-foreground">Features</a><a href="#how" className="transition-colors hover:text-foreground">How it works</a><a href="#analytics" className="transition-colors hover:text-foreground">Analytics</a></div><div className="flex items-center gap-2"><Link href="/login" className="hidden px-3 py-2 text-sm text-muted-foreground transition-colors hover:text-foreground sm:block">Log in</Link><Link href="/register" className="group inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-px hover:brightness-110">Get started <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" /></Link></div></nav>
    <section id="product" className="relative mx-auto max-w-6xl px-5 pb-24 pt-20 lg:grid lg:grid-cols-[1fr_.88fr] lg:items-center lg:gap-16 lg:px-8 lg:pb-32 lg:pt-28"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[36rem] opacity-70 [background-image:radial-gradient(circle_at_75%_15%,rgba(82,39,255,.18),transparent_26rem),radial-gradient(circle_at_25%_20%,rgba(255,159,252,.06),transparent_20rem)]" /><div className="animate-rise"><div className="mb-7 inline-flex items-center gap-2 border border-primary/25 bg-primary/10 px-3 py-1.5 font-mono text-[11px] uppercase tracking-[.16em] text-accent"><Sparkles className="size-3.5" /> Lead operations, made intelligent</div><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[1.02] tracking-[-.06em] md:text-7xl lg:text-[5.7rem]">Turn every lead<br />into an <span className="gradient-text">opportunity.</span></h1><p className="mt-7 max-w-xl text-pretty text-lg leading-8 text-muted-foreground">Capture, qualify, prioritize, and understand your leads with a workspace built for modern revenue teams.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/register" className="group inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-px hover:brightness-110">Get started <ArrowRight className="size-4 transition-transform group-hover:translate-x-0.5" /></Link><a href="#how" className="group inline-flex items-center gap-2 rounded-md border border-border bg-card/40 px-5 py-3 text-sm font-medium transition-colors hover:bg-muted">See how it works <ChevronRight className="size-4 transition-transform group-hover:translate-x-0.5" /></a></div></div><div className="mt-14 lg:mt-0"><ProductPreview /></div></section>
    <section className="border-y border-border bg-card/35 px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Less noise. More signal.</p><h2 className="mt-4 max-w-lg text-4xl font-semibold tracking-tight">Your leads deserve a clearer path forward.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Leads AI keeps the details, priorities, and next steps in one place so your team can focus on the conversations that matter.</p></div><div className="grid gap-3 sm:grid-cols-2">{['One workspace for every lead', 'Priorities your team can trust', 'Visibility into pipeline momentum', 'A foundation for automation'].map((item) => <div key={item} className="surface flex items-start gap-3 p-5"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-primary/15 text-primary"><Check className="size-3.5" /></span><p className="text-sm font-medium">{item}</p></div>)}</div></div></section>
    <section id="how" className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">How it works</p><h2 className="mt-4 max-w-2xl text-4xl font-semibold tracking-tight">A focused operating system for your pipeline.</h2><div className="mt-12 grid gap-8 md:grid-cols-4">{steps.map(([num, title, body]) => <article key={num} className="group border-t border-border pt-5"><span className="font-mono text-xs text-accent">{num}</span><h3 className="mt-10 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div></section>
    <section id="features" className="border-y border-border bg-card/35 px-5 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">The workspace</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-2xl text-4xl font-semibold tracking-tight">Everything your pipeline needs today, with room to grow.</h2><Link href="/register" className="text-sm font-medium text-accent hover:underline">Explore the workspace <ArrowRight className="ml-1 inline size-4" /></Link></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({ title, body, icon: Icon, badge }) => <article key={title} className="surface min-h-64 p-6 transition-transform hover:-translate-y-1"><Icon className="size-5 text-primary" /><div className="mt-12 flex items-center gap-2"><h3 className="font-semibold">{title}</h3>{badge && <span className="rounded-full border border-accent/30 px-2 py-0.5 font-mono text-[9px] uppercase tracking-wider text-accent">{badge}</span>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{body}</p></article>)}</div></div></section>
    <section id="analytics" className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="surface overflow-hidden p-6 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Analytics</p><h2 className="mt-3 text-3xl font-semibold">Understand what moves your pipeline.</h2></div><span className="border border-border px-3 py-1 text-xs text-muted-foreground">Personalized after sign in</span></div><div className="mt-10 grid gap-3 md:grid-cols-3"><div className="rounded-md border border-border bg-muted/35 p-5"><p className="text-sm text-muted-foreground">Real lead volume</p><p className="mt-3 text-sm leading-6 text-muted-foreground">See the exact number of leads in your workspace.</p></div><div className="rounded-md border border-border bg-muted/35 p-5"><p className="text-sm text-muted-foreground">Status distribution</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Understand how opportunities move through your pipeline.</p></div><div className="rounded-md border border-border bg-muted/35 p-5"><p className="text-sm text-muted-foreground">Priority signals</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Focus attention where it matters most.</p></div></div></div></section>
    <section className="mx-auto max-w-6xl px-5 pb-28 lg:px-8"><div className="relative overflow-hidden bg-primary px-6 py-16 text-primary-foreground md:px-12"><div className="relative max-w-xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-primary-foreground/70">Start with clarity</p><h2 className="mt-5 text-4xl font-semibold tracking-tight md:text-5xl">Make every lead easier to act on.</h2><p className="mt-5 text-lg leading-8 text-primary-foreground/75">Build a pipeline your team can see, trust, and improve.</p><Link href="/register" className="mt-8 inline-flex items-center gap-2 rounded-md bg-primary-foreground px-5 py-3 text-sm font-semibold text-primary transition-transform hover:-translate-y-px">Get started <ArrowRight className="size-4" /></Link></div></div></section>
    <footer className="border-t border-border px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-4 text-sm text-muted-foreground md:flex-row"><span>© 2026 Leads AI</span><span>Lead operations, made intelligent.</span></div></footer>
  </main>
}
